services:

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: django_backend_demo
    command: bash -c "sh entrypoint.sh"
    volumes: 
      - ./backend:/app
      - media_data:/app/media
    expose:
      - 8000
    environment:
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: playvisiondb
      SEED_DB: "false"
    depends_on:
      - db
  nginx:
    image: nginx:stable
    container_name: nginx_server_demo
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - media_data:/var/www/images
      - ./frontend/dist/frontend:/usr/share/nginx/html:ro
    depends_on:
      - backend

  db:
    image: postgres:15
    container_name: postgres_db_demo
    restart: always
    environment: 
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: playvisiondb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  media_data:
  postgres_data: